version: '3.3'
services:

  db:
    env_file:
      - ../backend/foodgram/.env
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always

  web:
    build:
      context: ../backend/foodgram/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - db
    env_file:
      - ../backend/foodgram/.env

  frontend:
    build:
      context: ../frontend/
      dockerfile: Dockerfile
    volumes:
      - frontend_data:/app/build/
    depends_on:
      - web

  nginx:
    image: nginx:1.19.6
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_data:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    restart: always
    depends_on:
      - web
      - frontend

volumes:
  postgres_data:
  static_value:
  media_value:
  frontend_data:
