# Generated by Django 2.2.19 on 2022-08-22 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinguserlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_in_shoplist', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, имеющий рецепт в Списке покупок'),
        ),
        migrations.AddField(
            model_name='recipetagrelationship',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_tags', to='recipes.Recipe', verbose_name='Рецепт'),
        ),
        migrations.AddField(
            model_name='recipetagrelationship',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_tags', to='recipes.Tag', verbose_name='Тег'),
        ),
        migrations.AddField(
            model_name='recipeingredientrelationship',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_in_recipe', to='recipes.Ingredient', verbose_name='ингредиент'),
        ),
        migrations.AddField(
            model_name='recipeingredientrelationship',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_in_recipe', to='recipes.Recipe', verbose_name='рецепт'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(db_index=True, related_name='ingredients_recipes', through='recipes.RecipeIngredientRelationship', to='recipes.Ingredient', verbose_name='ингредиент'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(db_index=True, through='recipes.RecipeTagRelationship', to='recipes.Tag', verbose_name='тег'),
        ),
        migrations.AddField(
            model_name='favoritesrecipesuserlist',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorit_recipe', to='recipes.Recipe', verbose_name='Избранный рецепт определенного пользователя'),
        ),
        migrations.AddField(
            model_name='favoritesrecipesuserlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorit_recipe', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, имеющий избранные рецепты'),
        ),
        migrations.AddConstraint(
            model_name='shoppinguserlist',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_relationships_user_shoplist'),
        ),
        migrations.AddConstraint(
            model_name='recipetagrelationship',
            constraint=models.UniqueConstraint(fields=('tag', 'recipe'), name='unique_relationships_tag_recipe'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredientrelationship',
            constraint=models.UniqueConstraint(fields=('ingredient', 'recipe'), name='unique_relationships_ingredient_recipe'),
        ),
        migrations.AddConstraint(
            model_name='favoritesrecipesuserlist',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_relationships_user_fav_recipe'),
        ),
    ]
