# Generated by Django 4.0 on 2021-12-30 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('recipes', '0002_initial')]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='shopping_cart',
            new_name='recipe',
        )
    ]
