# Generated by Django 3.2.5 on 2022-01-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('users', '0001_initial')]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Создан'),
        )
    ]
